chore: setup the page layout , the mobile and the desktop view
Kareem24/rock-paper pull request #1
Opened 2023-09-20 07:38 UTC by Kareem24

Structure the layout of the main page,
For both desktop and mobile view

2023-09-20 08:16 UTC, BasitKorede commented
![image](https://github.com/Kareem24/rock-paper/assets/69877769/2c186668-9afd-49c3-942a-871097c5b3e6)

##### This shouldn't be the design for the mobile screen.


See https://www.frontendmentor.io/challenges/rock-paper-scissors-game-pTgwgvgH for the correct design.

2023-09-20 08:36 UTC, BasitKorede requested changes
Good job done  Mr @Kareem24 , but unfortunately, there are still some changes to be made.
- The pull request description isn't descriptive enough.  Let's try to add all changes made in this particular branch.
- I noticed the test plan forum wasn't in use either.
let's make sure to add a test plan. this will entail how someone viewing the PR can access and test the project being done. Below is an example of what a test plan should look like.
![image](https://github.com/Kareem24/rock-paper/assets/69877769/52740114-55b9-4ef0-bcaa-2c4e272ca5d7)

2023-09-20 08:36 UTC, BasitKorede commented on src/components/Mainpage.jsx
> +      <header className='flex justify-between py-1 px-3 border-headerOutline rounded md:w-[60%] w-[90%] border m-auto items-center'>
I would prefer we use tailwind values for our CSS properties, all values given to the properties in most occurrences have their tailwind representation. 
eg `w-[60]` should be  `w-3/5`

2023-09-20 08:36 UTC, BasitKorede commented on tailwind.config.js
> +        end: 'hsl(237, 49%, 15%)',
can you please explain the reason for this in the config file? I don't know what this is you can add your comment below this comment. Thank you

2023-09-20 10:59 UTC, Kareem24 commented on tailwind.config.js
> +        end: 'hsl(237, 49%, 15%)',
I'm setting the color variable, so I can access them easily on my code

2023-09-21 12:42 UTC, BasitKorede approved these changes
Good job done 🥳

2023-09-21 13:48 UTC, merged